/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package architecture.diagram

import com.structurizr.export.IndentingWriter

class Library {
    private val identWriter: IndentingWriter = IndentingWriter()
}
